### ISSUE TITLE
Add TALISKER_NETWORKS to relevant services

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/deployment-configs#116]
Add `TALISKER_NETWORKS` environment variable to the config for relevant services, to allow querying from all internal IPs:

```
TALISKER_NETWORKS='10.0.0.0/8 172.16.0.0/12 192.168.0.0/16'
```

To services:

- [x] snapcraft.io
- [x] insights.ubuntu.com
- [ ] cn.ubuntnu.com
- [ ] www.canonical.com
- [ ] developer.ubuntu.com
- [ ] maas.io

**Comment by tbille** [comment]
This should be checked with IS, they did it for a few services (snapcraft.io, blog)
