### ISSUE TITLE
Create endpoint for snapcraft-io.prod-comms.kubernetes-ingress.canonical.com

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/deployment-configs#123]
Ready for squid to point to, we should create a new endpoint for snapcraft at snapcraft-io.prod-comms.kubernetes-ingress.canonical.com.

This should *not* use TLS, and it should be only accessible from the IP range for the Squid server, and possible the IP range for the VPN.

**Comment by jkfran** [comment]
@nottrobin can this be closed?

**Comment by nottrobin** [comment]
Yeah this is way outdated. We have content-cache now, which doesn't require any of this nonsense.
