### ISSUE TITLE
Confirm the ideal Squid configuration

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/deployment-configs#139]
When playing around with the squid installation created in https://portal.admin.canonical.com/C109653/, we discovered that it didn't cache anything with a `max-age` less than 1 minute. This is not acceptable.

We should check that the Squid cache behaves as we'd expect in that it will:

- cache large objects
- cache objects with a `max-age` any greater than 0
- refresh the cache in the background (don't delay the response
- honours `stale-if-error` and `stale-while-revalidate`
- honours `private`

To check this we should experiment with a local squid cache with similar rules. For this purpose, I set up https://github.com/nottrobin/squid-caching-experiment

**Comment by tbille** [comment]
This needs to be discuss with Content cache.

**Comment by nottrobin** [comment]
I can add an update here, with regards to content-cache:

It support both `stale-while-revalidate` and `stale-if-error`, and therefore it can do background refreshes. It respects `private`, and I don't think it has the 1 minute minimum on max-age.

It's maximum object size is [1MB for most sites and 10MB for assets](https://portal.admin.canonical.com/C125530/), but that might not be enough and we may need to request it be extended further.
