### ISSUE TITLE
Apply the ideal configuration to our Squid installation

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/deployment-configs#140]
Apply the squid configuration decided in #139 to the Squid cache set up in #138. This probably means submitting a Merge Proposal to either https://bazaar.launchpad.net/~canonical-sysadmins/canonical-is-charms/ssl-squid-reverseproxy/ or https://bazaar.launchpad.net/~canonical-is/canonical-mojo-specs/trunk/

**Comment by tbille** [comment]
This was resolved with content cache
