### ISSUE TITLE
Use squid proxy for all services

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/deployment-configs#280]
In https://github.com/canonical-web-and-design/deployment-configs/pull/278#pullrequestreview-313661442 we made the decision to leave the `useProxy` configurable option, as at present some services use the proxy and some don't.

However, ultimately we definitely want all services to use the proxy, so we have consistency, and then remove the `useProxy` config option, as we will no longer need it.

We should do this as soon after https://github.com/canonical-web-and-design/deployment-configs/pull/278 is merged as possible.

**Comment by tbille** [comment]
content cache resolves this issue.
