### ISSUE TITLE
Use /_status/check for the readinessProbe in all services

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/deployment-configs#281]
Currently our services use various different endpoints for the readinessProbe - `/`, `/_status/check`, `/_status/ping`. In https://github.com/canonical-web-and-design/deployment-configs/pull/278#pullrequestreview-313664559 we decided to leave this difference alone, to limit the scope of that huge PR.

However, as soon as that PR is merged as is practical, we should make this URL consistent across all services, and remove the `readinessPath` option.

**Comment by carkod** [comment]
Status checks have been removed, I don't think this is still relevant. Reopen if this is still relevant
