### ISSUE TITLE
Make sure www.* always points to the root domain

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/deployment-configs#311]
Please make sure www.site.com points to site.com

**Comment by jkfran** [comment]
Hey @pmahnke ,

I think we are already doing this, is this issue because some specific case that does not work?

**Comment by nottrobin** [comment]
@pmahnke I believe, as @jkfran said, we are always routing `www.{domain}` to `{domain}` if such a request comes into our k8s cluster. If there's a case where this isn't happening, I suspect it's more likely to be that the DNS for `www.{domain}` isn't pointing to our cluster - which would need an RT to IS to resolve.

**Comment by pmahnke** [comment]
It was with anbox. The press release pointed to www. And didn't resolve, so
I filed this.

**Comment by nottrobin** [comment]
@pmahnke that appears to be fixed now. I don'tt think we did anything - do you know if IS did?

**Comment by tbille** [comment]
This is part of the konf script
